### ISSUE TITLE
New functionality within DrScratchTool

### ISSUE THREAD

**Issue by titua77** [nathan/getsb2#2]
Hi Nathan,

We are working in a new tool for analyzing scratch projects, the tool is called DrScratch, you can see it in: http://drscratchpre.programamos.es/

currently, the analysis begins when an user upload a project and then DrScratch valuates the Scratch projects in a variety of computational areas.

We are glad of finding getsb2, because it provides us a new functionality, the user can simply give the idproject, so it is not necessary uploading a project, and the usability will be higher.

We have seen your repository, could you tell me if the repository has the last version?

Regards,
Cristian

**Comment by nathan** [comment]
Yeah, the version on Heroku is 2393a11f6ee9d827c7691afe7d99b9b3f66e8114 (same as master, currently).
